/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/furnitature/chair_1.glb 
Author: Aaditya Bhardwaj (https://sketchfab.com/Bhaaditya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chair-01-70d8e0b1f7ba4aa1ba98c65819015442
Title: chair_01
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair1(props) {
  const { nodes, materials } = useGLTF('./furnitature/chair_1.glb')
  return (
    <group {...props.mainProps} castShadow scale={[2, 2, 2]}  dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.012}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow geometry={nodes.null__aiStandardSurface2_0.geometry} position={[387.56, -53.918, -2809.188]} rotation={[0, Math.PI / 2, 0]} scale={2.862} >
            <meshStandardMaterial {...props.textureProps}/>
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./furnitature/chair_1.glb')
