/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/furnitature/chair_2.glb 
Author: Dyslexic3 (https://sketchfab.com/Dyslexic3)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sborg-chair-dfb7c3b51e264b5083dc28450e55c2a0
Title: Søborg Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair2(props) {
  const { nodes, materials } = useGLTF('./furnitature/chair_2.glb')
  return (
    <group {...props.mainProps} castShadow  scale={[2.5, 2.5, 2.5]} dispose={null}>
      <group position={[0.048, 0.032, 0.019]} rotation={[-Math.PI / 2, 0, 0]} scale={1.238}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.003, 0]} rotation={[0, -0.448, 0.163]} scale={0.194}>
            <group position={[-0.367, 2.919, -0.287]} rotation={[-0.031, 0.002, -0.361]} scale={0.006}>
              <mesh castShadow geometry={nodes.Object_10.geometry} material={materials.Material}>
                <meshStandardMaterial {...props.textureProps} />
              </mesh>
              <mesh castShadow geometry={nodes.Object_11.geometry} material={materials['Material.005']} >
              <meshStandardMaterial {...props.textureProps} />
              </mesh>
            </group>
            <mesh castShadow geometry={nodes.Object_4.geometry} material={materials.WoodQuarteredChiffon001_3K} >
            <meshStandardMaterial {...props.textureProps} />
            </mesh>
            <mesh castShadow geometry={nodes.Object_6.geometry} material={materials.WoodQuarteredChiffon001_3K} position={[0.542, 3.348, -1.012]} rotation={[1.304, -0.158, -0.043]} >                <meshStandardMaterial {...props.textureProps} />
            </mesh>
            <mesh castShadow geometry={nodes.Object_8.geometry} material={materials.WoodQuarteredChiffon001_3K} position={[0.353, 2.205, 0.188]} rotation={[0, 0, -0.163]} >                <meshStandardMaterial {...props.textureProps} />
            </mesh>
            <mesh castShadow geometry={nodes.Object_13.geometry} material={materials.Material} position={[-0.366, 2.93, -0.287]} rotation={[-0.031, 0.002, -0.361]} scale={0.006} >                <meshStandardMaterial {...props.textureProps} />
            </mesh>
            <mesh castShadow geometry={nodes.Object_15.geometry} material={materials.WoodQuarteredChiffon001_3K} position={[0.267, 1.621, 0.945]} rotation={[-0.066, 0.011, -0.163]} >                <meshStandardMaterial {...props.textureProps} />
            </mesh>
            <mesh castShadow geometry={nodes.Object_17.geometry} material={materials.WoodQuarteredChiffon001_3K} position={[0.261, 1.551, -0.924]} rotation={[0.08, -0.013, -0.163]} >                <meshStandardMaterial {...props.textureProps} />
            </mesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./furnitature/chair_2.glb')
