/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/furnitature/table_2.glb 
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/jenson-extending-dining-table-dark-stain-oak-1e7fe455a440418694497f2d4a7a2ef9
Title: Jenson Extending Dining Table, Dark Stain Oak
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Table2(props) {
  const { nodes, materials } = useGLTF('./furnitature/table_2.glb')
  return (
    <group {...props.mainProps} scale={[0.03, 0.03, 0.03]} dispose={null}>
      <group position={[0, 0.1, 0]}>
        <mesh castShadow geometry={nodes.Jenson_Extending_Table_DarkStainedOak_DARK_STAIN_OAK_0.geometry}  position={[55.616, -6.294, -169.421]} >
          <meshStandardMaterial {...props.textureProps}/>
        </mesh>
      </group>
      <mesh geometry={nodes.Plane001_FLOOR_0.geometry} material={materials.FLOOR} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./furnitature/table_2.glb')
