/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/furnitature/table_1.glb 
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/joseph-dining-table-dark-stain-ash-9cddea6e641d4d8e83a5221370b53cef
Title: Joseph Dining Table, Dark Stain Ash
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
// material={materials.DARK_STAINED_ASH}
export function Table1(props) {
  const { nodes, materials } = useGLTF('./furnitature/table_1.glb')
  return (
    <group {...props.mainProps} scale={[0.03, 0.03, 0.03]} dispose={null}>
      <group position={[0, -0.01, 0]}  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh castShadow geometry={nodes.Joseph_Dining_Table_Dark_Stain_Ash_DARK_STAINED_ASH_0.geometry}  position={[38.152, 77.788, 0]} >
          <meshStandardMaterial {...props.textureProps} />
        </mesh>

      </group>
      <mesh geometry={nodes.Plane001_FLOOR_0.geometry} material={materials.FLOOR} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./furnitature/table_1.glb')
